export const AGENT_ZERO_BASE_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_bridgeSender', type: 'address' },
      { internalType: 'address', name: '_bridgeReceiver', type: 'address' },
      { internalType: 'address', name: '_genLayerTarget', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'AgentNotActive', type: 'error' },
  { inputs: [], name: 'AgentNotFound', type: 'error' },
  { inputs: [], name: 'AlreadyRegistered', type: 'error' },
  { inputs: [], name: 'InvalidProviderType', type: 'error' },
  { inputs: [], name: 'NoActiveAgents', type: 'error' },
  { inputs: [], name: 'NotAssignedAgent', type: 'error' },
  { inputs: [], name: 'NotRegistered', type: 'error' },
  { inputs: [], name: 'NotTaskRequester', type: 'error' },
  { inputs: [], name: 'OnlyBridgeReceiver', type: 'error' },
  { inputs: [], name: 'OnlyOwner', type: 'error' },
  { inputs: [], name: 'TaskNotCompleted', type: 'error' },
  { inputs: [], name: 'TaskNotDisputed', type: 'error' },
  { inputs: [], name: 'TaskNotInProgress', type: 'error' },
  { inputs: [], name: 'TaskNotMatched', type: 'error' },
  { inputs: [], name: 'TaskNotOpen', type: 'error' },
  // Events
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' }],
    name: 'AgentDeactivated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' },
      { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
    ],
    name: 'AgentRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' }],
    name: 'AgentUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' },
      { indexed: false, internalType: 'int8', name: 'trustAdjustment', type: 'int8' },
    ],
    name: 'AuditCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' },
      { indexed: false, internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
    ],
    name: 'AuditRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' }],
    name: 'DisputeRaised',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: false, internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
    ],
    name: 'DisputeRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: false, internalType: 'string', name: 'verdict', type: 'string' },
    ],
    name: 'DisputeResolved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: false, internalType: 'bytes32', name: 'messageId', type: 'bytes32' },
    ],
    name: 'MatchRequested',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' }],
    name: 'ResultApproved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' }],
    name: 'ResultSubmitted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' },
    ],
    name: 'TaskAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: true, internalType: 'address', name: 'requester', type: 'address' },
    ],
    name: 'TaskCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint32', name: 'taskId', type: 'uint32' },
      { indexed: true, internalType: 'uint32', name: 'agentId', type: 'uint32' },
    ],
    name: 'TaskMatched',
    type: 'event',
  },
  // Functions
  {
    inputs: [{ internalType: 'uint32', name: '_taskId', type: 'uint32' }],
    name: 'acceptTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'agentCount',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_taskId', type: 'uint32' }],
    name: 'approveResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_taskId', type: 'uint32' }],
    name: 'disputeResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string', name: '_requiredCapability', type: 'string' },
      { internalType: 'string', name: '_preferredProvider', type: 'string' },
    ],
    name: 'createTask',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'deactivateAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_agentId', type: 'uint32' }],
    name: 'getAgent',
    outputs: [
      {
        components: [
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'string', name: 'endpoint', type: 'string' },
          { internalType: 'string', name: 'capabilities', type: 'string' },
          { internalType: 'string', name: 'providerType', type: 'string' },
          { internalType: 'uint32', name: 'trustScore', type: 'uint32' },
          { internalType: 'uint32', name: 'totalTasks', type: 'uint32' },
          { internalType: 'uint32', name: 'successfulTasks', type: 'uint32' },
          { internalType: 'bool', name: 'active', type: 'bool' },
        ],
        internalType: 'struct AgentZeroBase.AgentInfo',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_owner', type: 'address' }],
    name: 'getAgentByOwner',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAgentCount',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint32', name: '_taskId', type: 'uint32' }],
    name: 'getTask',
    outputs: [
      {
        components: [
          { internalType: 'uint32', name: 'taskId', type: 'uint32' },
          { internalType: 'address', name: 'requester', type: 'address' },
          { internalType: 'string', name: 'description', type: 'string' },
          { internalType: 'string', name: 'requiredCapability', type: 'string' },
          { internalType: 'uint32', name: 'assignedAgentId', type: 'uint32' },
          { internalType: 'string', name: 'status', type: 'string' },
          { internalType: 'string', name: 'result', type: 'string' },
          { internalType: 'string', name: 'creatorType', type: 'string' },
          { internalType: 'string', name: 'preferredProvider', type: 'string' },
        ],
        internalType: 'struct AgentZeroBase.Task',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getTaskCount',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string', name: '_endpoint', type: 'string' },
      { internalType: 'string', name: '_capabilities', type: 'string' },
      { internalType: 'string', name: '_providerType', type: 'string' },
    ],
    name: 'registerAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_agentId', type: 'uint32' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'requestAudit',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_taskId', type: 'uint32' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'requestDisputeResolution',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_taskId', type: 'uint32' },
      { internalType: 'bytes', name: '_options', type: 'bytes' },
    ],
    name: 'requestMatch',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint32', name: '_taskId', type: 'uint32' },
      { internalType: 'string', name: '_result', type: 'string' },
    ],
    name: 'submitResult',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'taskCount',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: '_name', type: 'string' },
      { internalType: 'string', name: '_description', type: 'string' },
      { internalType: 'string', name: '_endpoint', type: 'string' },
      { internalType: 'string', name: '_capabilities', type: 'string' },
    ],
    name: 'updateAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
